# This is a basic workflow for pull and build CTM using GitHub Actions
name: [auto]-pull-install-source-code

# Controls when the action will run. Triggers the workflow on push request
# events but only for the main branch
on:
  push:
    branches:
      - main
      
# A workflow run is made up of one or more jobs that can run sequentially or in parallel    
jobs:
  # The first job in this workflow is named build-on-ubuntu
  pull-build-install:
    runs-on: ubuntu-latest
  
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps: 
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Step 1 - Checkout main branch from GitHub
        uses: actions/checkout@v2      
    
      # Runs a single command using the runners shell
      - name: Step 2 - Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
             java-version: 1.8     
     
      - name: Step 3 - Have GitHub Actions Build Maven Project
        run: |
          mvn -f pom.xml clean install
      # Uncomment if you want to meve  the jar files # mkdir staging && cp target/*.jar staginggggg
          
      - name: Step 4 - Set up a cache for Maven
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
          
     
      - name: Step 5 - copy file via ssh key
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
          PORT: 22
          KEY: ${{ secrets.SSH_KEY }}
        with:
          source: "*"
          target: "/home/gitactionuser/test"        

      
