# This is a basic workflow for build and run docker file
name: build and run docker file using GitHub Actions

# Controls when the action will run. Triggers the workflow on push request
# events but only for the main branch
on:
  push:
    branches:
      - main
      
# A workflow run is made up of one or more jobs that can run sequentially or in parallel    
jobs:
  # The first job in this workflow is named build-on-ubuntu
  build-on-ubuntu:
    runs-on: ubuntu-latest
  
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps: 
    
      - name: Step 1 - copy file via ssh key
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
          PORT: 22
          KEY: ${{ secrets.SSH_KEY }}
        with:
           script: |
             whoami
             ls -al
