name: CTM deployment workflow - pull from repo
on:
  push:
    branches:
      - main
jobs:
  pull-ctm-job:
    name: pull-ctm-job
    runs-on: ubuntu-latest
    steps:    
      - uses: actions/checkout@v2
      - name: Deploy source-code
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
          PORT: 22
          KEY: ${{ secrets.SSH_KEY }}
        with:
          source: "target/*"
          target: "/home/gitactionuser/test"
    
