name: CTM deployment workflow - pull from repo
on:
  push:
    branches:
      - main    
jobs:
  build-on-ubuntu:
    runs-on: ubuntu-latest
    steps:         
      - name: Step 2 - Checkout the main GitHub branch.
      - uses: actions/checkout@v2      
      - name: Step 3 - Deploy source-code to ${{ secrets.SSH_HOST }} host
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
          PORT: 22
          KEY: ${{ secrets.SSH_KEY }}
        with:
          source: "*"
          target: "/home/gitactionuser/test"
